/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./s21_math_test.check" instead.
 */

#include <check.h>

#line 1 "./s21_math_test.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <limits.h>
#include <math.h>

#include "s21_math.h"


START_TEST(s21_fabs_test1)
{
#line 12
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = fabs(i * M_PI / 18.0);
            y2 = s21_fabs(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_fabs_test2)
{
#line 19
    ck_assert_ldouble_nan(fabs(NAN)); 
    ck_assert_ldouble_nan(s21_fabs(NAN)); 

}
END_TEST

START_TEST(s21_floor_test1)
{
#line 23
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = floor(i * M_PI / 18.0);
            y2 = s21_floor(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_floor_test2)
{
#line 30
    ck_assert_ldouble_nan(floor(NAN));
    ck_assert_ldouble_nan(s21_floor(NAN));

}
END_TEST

START_TEST(s21_ceil_test1)
{
#line 34
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = ceil(i * M_PI / 18.0);
            y2 = s21_ceil(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_ceil_test2)
{
#line 41
    ck_assert_ldouble_nan(ceil(NAN));
    ck_assert_ldouble_nan(s21_ceil(NAN));

}
END_TEST

START_TEST(s21_ceil_test3)
{
#line 45
    double y1, y2, tol =0.000001;
    y1 = ceil(0.0);
    y2 = s21_ceil(0.0);
    ck_assert_ldouble_eq_tol(y1, y2,tol);

}
END_TEST

START_TEST(s21_fmod_test1)
{
#line 51
    double y1, y2, tol = 0.000001;
    for (int i = -18; i <= 18 && i != 0; i++) {
        for (int j = 18; j >= -18 && j != 0; j--) {
            y1 = fmod(i * M_PI / 18.0, j);
            y2 = s21_fmod(i * M_PI / 18.0, j);
            ck_assert_ldouble_eq_tol(y1, y2,tol);}
        }

}
END_TEST

START_TEST(s21_fmod_test2)
{
#line 60
    ck_assert_ldouble_nan(fmod(NAN,NAN));
    ck_assert_ldouble_nan(s21_fmod(NAN,NAN));

}
END_TEST

START_TEST(s21_pow_test1)
{
#line 64
    double y1, y2, tol =0.000001;
    for (int i = -10; i <= 10 && i != 0; i++) {
        for (int j = 10; j >= -10 && j != 0;j--){
            y1 = pow(i * M_PI / 18.0, j);
            y2 = s21_pow(i * M_PI / 18.0, j);
            ck_assert_ldouble_eq_tol(y1, y2,tol);}
    }
}
END_TEST

START_TEST(s21_pow_test2)
{
#line 72
    ck_assert_ldouble_nan(s21_pow(NAN, NAN));
    ck_assert_ldouble_eq(s21_pow(NAN, 0), 1);
    ck_assert_ldouble_eq(s21_pow(1, NAN), 1);

}
END_TEST

START_TEST(s21_exp_test1)
{
#line 77
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = exp(i * M_PI / 18.0);
            y2 = s21_exp(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_exp_test2)
{
#line 84
    ck_assert_ldouble_nan(exp(NAN));
    ck_assert_ldouble_nan(s21_exp(NAN));

}
END_TEST

START_TEST(s21_sqrt_test1)
{
#line 88
    double y1, y2, tol =0.000001;
    for (int i = -18; i < 0; i++) {
            y2 = s21_sqrt(i * M_PI / 18.0);
            ck_assert_ldouble_nan(y2);
    }
    for (int i = 1; i <= 18; i++) {
            y1 = sqrt(i * M_PI / 18.0);
            y2 = s21_sqrt(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_sqrt_test2)
{
#line 99
    ck_assert_ldouble_nan(sqrt(NAN));
    ck_assert_ldouble_nan(s21_sqrt(NAN));

}
END_TEST

START_TEST(s21_log_test1)
{
#line 103
    double y1, y2, tol =0.000001;
    for (int i = 1; i <= 18; i++) {
            y1 = log(i * M_PI / 18.0);
            y2 = s21_log(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_log_test2)
{
#line 110
    ck_assert_ldouble_nan(log(NAN));
    ck_assert_ldouble_nan(s21_log(NAN));

}
END_TEST

START_TEST(s21_log_test3)
{
#line 114
    ck_assert_ldouble_infinite(log(0));
    ck_assert_ldouble_infinite(s21_log(0));

}
END_TEST

START_TEST(s21_log_test4)
{
#line 118
    ck_assert_ldouble_nan(log(-1));
    ck_assert_ldouble_nan(s21_log(-1));


}
END_TEST

START_TEST(s21_sin_test1)
{
#line 123
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = sin(i * M_PI / 18.0);
            y2 = s21_sin(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_sin_test2)
{
#line 130
    ck_assert_ldouble_nan(sin(NAN));
    ck_assert_ldouble_nan(s21_sin(NAN));
}
END_TEST

START_TEST(s21_sin_test3)
{
#line 133
    ck_assert_ldouble_nan(s21_sin(INFINITY));
    
}
END_TEST

START_TEST(s21_cos_test1)
{
#line 136
    double y1, y2, tol =0.000001;
    for (int i = -18; i <= 18; i++) {
            y1 = cos(i * M_PI / 18.0);
            y2 = s21_cos(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
        }
}
END_TEST

START_TEST(s21_cos_test2)
{
#line 143
    ck_assert_ldouble_nan(cos(NAN));
    ck_assert_ldouble_nan(s21_cos(NAN));

}
END_TEST

START_TEST(s21_tan_test1)
{
#line 147
    double y1, y2, tol =0.000001;
    for (int i = -18; i < -10; i++) {
            y1 = tan(i * M_PI / 18.0);
            y2 = s21_tan(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
        }

}
END_TEST

START_TEST(s21_tan_test2)
{
#line 155
    ck_assert_ldouble_nan(tan(NAN));
    ck_assert_ldouble_nan(s21_tan(NAN));

}
END_TEST

START_TEST(s21_asin_test1)
{
#line 159
    double y1, y2, tol =0.000001;
    for (int i = -18; i < -5; i++) {
            
            y2 = s21_asin(i * M_PI / 18.0);
            ck_assert_ldouble_nan(y2);
    }
    for (int i = -5; i < 6; i++) {
            y1 = asin(i * M_PI / 18.0);
            y2 = s21_asin(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
    }
}
END_TEST

START_TEST(s21_asin_test2)
{
#line 171
    ck_assert_ldouble_nan(asin(INFINITY));
    ck_assert_ldouble_nan(s21_asin(INFINITY));
    ck_assert_ldouble_nan(s21_asin(-7));
    ck_assert_ldouble_nan(s21_asin(7));



}
END_TEST

START_TEST(s21_asin_test3)
{
#line 179
    ck_assert_ldouble_eq(s21_asin(0), 0);
    
}
END_TEST

START_TEST(s21_acos_test1)
{
#line 182
    double y1, y2, tol =0.000001;
    for (int i = -18; i < -6; i++) {
            y1 = acos(i * M_PI / 18.0);
            y2 = s21_acos(i * M_PI / 18.0);
            ck_assert_ldouble_nan(y2);
        }
    for (int i = -5; i <= 5; i++) {
            y1 = acos(i * M_PI / 18.0);
            y2 = s21_acos(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
        }

}
END_TEST

START_TEST(s21_acos_test2)
{
#line 195
    ck_assert_ldouble_nan(acos(NAN));
    ck_assert_ldouble_nan(s21_acos(NAN));
    ck_assert_ldouble_nan(s21_acos(-7));
    ck_assert_ldouble_nan(s21_acos(7));

}
END_TEST

START_TEST(s21_acos_test3)
{
#line 201
    ck_assert_ldouble_eq(s21_acos(1),0);
    

}
END_TEST

START_TEST(s21_atan_test1)
{
#line 205
    double y1, y2, tol =0.000001;
    for (int i = -18; i <18 ; i++) {
            y1 = atan(i * M_PI / 18.0);
            y2 = s21_atan(i * M_PI / 18.0);
            ck_assert_ldouble_eq_tol(y1, y2,tol);
        }

}
END_TEST

START_TEST(s21_atan_test2)
{
#line 213
    ck_assert_ldouble_nan(atan(NAN));
    ck_assert_ldouble_nan(s21_atan(NAN));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_fabs_test1);
    tcase_add_test(tc1_1, s21_fabs_test2);
    tcase_add_test(tc1_1, s21_floor_test1);
    tcase_add_test(tc1_1, s21_floor_test2);
    tcase_add_test(tc1_1, s21_ceil_test1);
    tcase_add_test(tc1_1, s21_ceil_test2);
    tcase_add_test(tc1_1, s21_ceil_test3);
    tcase_add_test(tc1_1, s21_fmod_test1);
    tcase_add_test(tc1_1, s21_fmod_test2);
    tcase_add_test(tc1_1, s21_pow_test1);
    tcase_add_test(tc1_1, s21_pow_test2);
    tcase_add_test(tc1_1, s21_exp_test1);
    tcase_add_test(tc1_1, s21_exp_test2);
    tcase_add_test(tc1_1, s21_sqrt_test1);
    tcase_add_test(tc1_1, s21_sqrt_test2);
    tcase_add_test(tc1_1, s21_log_test1);
    tcase_add_test(tc1_1, s21_log_test2);
    tcase_add_test(tc1_1, s21_log_test3);
    tcase_add_test(tc1_1, s21_log_test4);
    tcase_add_test(tc1_1, s21_sin_test1);
    tcase_add_test(tc1_1, s21_sin_test2);
    tcase_add_test(tc1_1, s21_sin_test3);
    tcase_add_test(tc1_1, s21_cos_test1);
    tcase_add_test(tc1_1, s21_cos_test2);
    tcase_add_test(tc1_1, s21_tan_test1);
    tcase_add_test(tc1_1, s21_tan_test2);
    tcase_add_test(tc1_1, s21_asin_test1);
    tcase_add_test(tc1_1, s21_asin_test2);
    tcase_add_test(tc1_1, s21_asin_test3);
    tcase_add_test(tc1_1, s21_acos_test1);
    tcase_add_test(tc1_1, s21_acos_test2);
    tcase_add_test(tc1_1, s21_acos_test3);
    tcase_add_test(tc1_1, s21_atan_test1);
    tcase_add_test(tc1_1, s21_atan_test2);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
